services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    stop_grace_period: 15s
    volumes:
    - mongo-data:/data/db

  app:
    build: .
    env_file:
      - .env
    container_name: authentication
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=${SESSION_SECRET}
      - SECRET=${SECRET}
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data: