name: Autenticação-moderna-node-express

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24.x ]

    steps:
    - uses: actions/checkout@v4
    - name : Build docker image
      run: docker build -t autenticacao-moderna-node-express .
    - name: Run Tests in Docker
      run: docker run --rm autenticacao-moderna-node-express npm run test
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm start
    - name: Test
      run: npm test